module.exports = [
	"mc.hypixel.net",
	"us.mineplex.com",
	"play.cubecraft.net",
	"2b2t.org",
	"hub.opblocks.com", // fun.opblocks.com
	"org.mc-complex.com", // msl.mc-complex.com
	"org.akumamc.net",
	"mcs.mchub.com",
	"8b8t.me",
	"6b6t.org",
	"play.mccentral.org",
	"mc.librecraft.com",
	"crankedmc.com",
	"vanillahub.net",
	"play.vulengate.com",
	"play.acesmp.net",
	"hub.penguin.gg",
	"org.earthmc.net",
	"hub.neocubest.com",
	"play.enderkraken.com",
	"firesteal.playsurvival.me",
	"mc.calicocaffe.net",
	"play.mcfalcon.org",
	"mccnetwork.uk",
	"9b9t.me",
	"mcsl.applecraft.org",
	"play.blossomcraft.org",
	"mc.advancius.net",
	"play.mlegacy.net",
	"mc.agemagic.ru",
	"mc.restartcraft.fun",
	"mc.minelandy.net",
	"play.migosmc.net", // go.migosmc.net
	"top.mcmcmc.net", // megaland.mcmcmc.net, vega.mcmcmc.net, rat.skybars.net
	"mc.fast-mc.ru",
	"mcfunny.net",
	"mc.nexcraft.me",
	"play.mcskill.net",
	"mc.mcskill.net",
	"gw-play.ru",
	"join.ml-mc.com",
	"msl.pixelmonrealms.com",
	"mcslj.pika.host",
	"play.fruitysmp.com",
	"play.alphamc.ru", // join.alphacraft.ru, sun.mcbatyacraft.ru
	"mc.playmine.org",
	"mc.musteryworld.ru",
	"top1.funnymc.net",
	"play.pokesaga.org",
	"play.jackpotmc.com",
	"play.smashmc.co",
	"mcslj.jartex.fun",
	"mcsl.zedarmc.com",
	"mc.elenox.net",
	"goodmc.ru",
	"vanilla.sparkcraft.ru",
	"herobrine.org",
	"sl.minecadia.com",
	"yupixworld.ru",
	"roleplay.ttp.su",
	"mc.undernova.ru",
	"morgenstern.top",
	"mc.vayland.net",
	"go.infplay.ru"
]